services:
  api-shared: &api-shared
    image: sniper-api:${VERSION:-latest}
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
      - ./license.lic:/app/license.lic:rw
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    profiles:
      - donotstart

  signal_matching:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "scripts/run_matching_service.py"]

  snapshot_scheduler:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "scripts/schedule_portfolio_snapshot.py"]

  trade:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/trade.py"]

  api:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/api/server.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 8000:8000

  frontend:
    image: sniper-frontend:${VERSION:-latest}
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_DISABLE_TURBOPACK=1
    ports:
      - "3000:3000"
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend
  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge
