services:
  api-shared: &api-shared
    image: sniper-api:${VERSION:-latest}
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
      - ./license.lic:/app/license.lic:rw
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    profiles:
      - donotstart

  # 数据库迁移服务
  db-migrate:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "-m", "alembic", "upgrade", "head"]
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  signal_matching:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/run_matching_service.py"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  snapshot_scheduler:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/schedule_portfolio_snapshot.py"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  trade:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/trade.py"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  api:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/api/server.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: sniper-frontend:${VERSION:-latest}
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_DISABLE_TURBOPACK=1
    volumes:
      - frontend_cache:/app/.next/cache
    ports:
      - "3000:3000"
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend
  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./scripts/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 9000:80
    depends_on:
      - frontend
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  frontend_cache:
