services:
  n8n-shared: &n8n-shared
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    volumes:
      - ./data/n8n_storage:/home/node/.n8n:rw
    env_file:
      - .env
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_HEALTH_CHECK_ACTIVE=true
    links:
      - redis
      - postgres
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
    profiles:
      - donotstart

  api-shared: &api-shared
    image: sniper-api:${VERSION:-latest}
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
      - ./license.lic:/app/license.lic:rw
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    profiles:
      - donotstart

  signal_matching:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "scripts/run_matching_service.py"]

  snapshot_scheduler:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "scripts/schedule_portfolio_snapshot.py"]

  trade:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/trade.py"]

  api:
    <<: *api-shared
    profiles: []
    command: ["uv", "run", "app/api/server.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 8000:8000

  frontend:
    image: sniper-frontend:${VERSION:-latest}
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_DISABLE_TURBOPACK=1
    ports:
      - "3000:3000"
    networks:
      - backend

  n8n:
    <<: *n8n-shared
    profiles: []
    ports:
      - "5678:5678"

  n8n-worker:
    <<: *n8n-shared
    profiles: []
    command: worker
    depends_on:
      - n8n
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend
  postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge
